### ISSUE TITLE
Make REPL mode

### ISSUE THREAD

**Issue by KronosTheLate** [svilupp/PromptingTools.jl#131]
Hi! Disclaimer: I have not yet used this package, and discovered it yesterday.

I was just thinking that for this package, a REPL mode would be fantastic! It could save the user from typing `ai""` in every call, display the current model in the promt, and other goodies. Also, `ai!` could be called automatically on subsequent inputs, until the user exits and reenters the REPL mode, or types `end` (mimicing the julia syntax to end a block), or something else.

It might even be very easy to make, using [ReplMaker](https://github.com/MasonProtter/ReplMaker.jl)!

**Comment by svilupp** [comment]
Perhaps this could be helpful: https://github.com/ThatcherC/ReplGPT.jl?

Or were you thinking about something else?

**Comment by KronosTheLate** [comment]
Oh, that is really cool! Yes, that is what I was imagining. Is that package and this very different in their goals? Why are they separate packages?

**Comment by svilupp** [comment]
It's a different scope (single chat vs. llm primitives for various workloads)

**Comment by cpfiffer** [comment]
I'll close this one for now as a "will not implement", since the package scope is different. PromptingTools.jl is better suited as building blocks for a REPL mode, and one such REPL already exists.

Feel free to open again if anyone disagrees!

**Comment by KronosTheLate** [comment]
That sounds reasonable, thanks!
